[WIP] refactor wrapper of SimpleArray
solvcon/solvcon pull request #123
Opened 2022-10-01 10:19 UTC by tigercosmos

move `TypeBroadcast` outside wrapper

2022-10-01 10:28 UTC, tigercosmos commented
I think this logic, copying array,  doesn't need to be inside the wrapper, the wrapper should just "wrap" things?

2022-10-01 14:19 UTC, yungyuc requested changes

2022-10-01 14:19 UTC, yungyuc commented on cpp/modmesh/buffer/TypeBroadcast.hpp
> +#include <pybind11/pybind11.h>
Code using pybind11 should live in the `python/` sub-directory.  Otherwise, pure C++ code will include the `Python.h` (like here).  `Python.h` alters a lot of things, requires to be included before everything else, and should not be included for pure C++ code.

2022-10-01 14:19 UTC, yungyuc commented on cpp/modmesh/buffer/TypeBroadcast.cpp
> +static void TypeBroadCast<T>::check_shape(SimpleArray<T> const & arr_out,
This is incorrect to put template implementation in a cpp file: https://stackoverflow.com/questions/115703/storing-c-template-function-definitions-in-a-cpp-file .  While forceful instantiation may be a workaround (but I do not like it), you do not do it either.

2022-10-03 11:11 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
@yungyuc 
This code will cause an error. 
seems there is a symbol for lambda, but it cannot be used in another place?
```log
In file included from /home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:30:
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp: In instantiation of ‘static void modmesh::python::TypeBroadcastImpl<T, D>::broadcast(modmesh::SimpleArray<U>&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool; D = bool]’:
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp:158:50:   required from ‘static void modmesh::python::TypeBroadcast<T>::broadcast(modmesh::SimpleArray<U>&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:329:36:   required from ‘static void modmesh::python::WrapSimpleArray<T>::broadcast_array_using_slice(modmesh::python::WrapSimpleArray<T>::wrapped_type&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool; modmesh::python::WrapSimpleArray<T>::wrapped_type = modmesh::SimpleArray<bool>]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:187:44:   required from ‘static void modmesh::python::WrapSimpleArray<T>::setitem_parser(modmesh::python::WrapSimpleArray<T>::wrapped_type&, const pybind11::args&) [with T = bool; modmesh::python::WrapSimpleArray<T>::wrapped_type = modmesh::SimpleArray<bool>]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:143:33:   required from ‘modmesh::python::WrapSimpleArray<T>::WrapSimpleArray(pybind11::module&, const char*, const char*) [with T = bool; pybind11::module = pybind11::module_]’
/home/mujin/modmesh/cpp/modmesh/python/common.hpp:266:29:   required from ‘static modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::wrapper_type& modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::commit(pybind11::module&, const char*, const char*) [with Wrapper = modmesh::python::WrapSimpleArray<bool>; Wrapped = modmesh::SimpleArray<bool>; Holder = std::unique_ptr<modmesh::SimpleArray<bool>, std::default_delete<modmesh::SimpleArray<bool> > >; WrappedBase = modmesh::SimpleArray<bool>; modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::wrapper_type = modmesh::python::WrapSimpleArray<bool>; pybind11::module = pybind11::module_]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:377:76:   required from here
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp:75:20: error: ‘modmesh::python::TypeBroadcastImpl<T, D>::broadcast<bool, bool>::<lambda(modmesh::python::TypeBroadcastImpl<bool, bool>::shape_type, int)>’ declared with greater visibility than the type of its field ‘modmesh::python::TypeBroadcastImpl<T, D>::broadcast<bool, bool>::<lambda(modmesh::python::TypeBroadcastImpl<bool, bool>::shape_type, int)>::<arr_in capture>’ [-Werror=attributes]
   75 |         copy_idx = [&](shape_type sidx, int dim)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   76 |         {
      |         ~           
   77 |             if (dim < 0)
      |             ~~~~~~~~~~~~
   78 |             {
      |             ~       
   79 |                 return;
      |                 ~~~~~~~
   80 |             }
      |             ~       
   81 | 
      |                     
   82 |             for (size_t i = 0; i < left_shape[dim]; ++i)
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   83 |             {
      |             ~       
   84 |                 sidx[dim] = i;
      |                 ~~~~~~~~~~~~~~
   85 | 
      |                     
   86 |                 size_t offset_in = 0;
      |                 ~~~~~~~~~~~~~~~~~~~~~
   87 |                 for (pybind11::ssize_t it = 0; it < arr_in.ndim(); ++it)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   88 |                 {
      |                 ~   
   89 |                     offset_in += arr_in.strides(it) / arr_in.itemsize() * sidx[it];
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   90 |                 }
      |                 ~   
   91 |                 const D * ptr_in = arr_new->data() + offset_in;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   92 | 
      |                     
   93 |                 size_t offset_out = 0;
      |                 ~~~~~~~~~~~~~~~~~~~~~~
   94 |                 for (size_t it = 0; it < arr_out.ndim(); ++it)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   95 |                 {
      |                 ~   
   96 |                     auto step = slices[it][2];
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
   97 |                     offset_out += arr_out.stride(it) * sidx[it] * step;
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   98 |                 }
      |                 ~   
   99 | 
      |                     
  100 |                 // NOLINTNEXTLINE(bugprone-signed-char-misuse, cert-str34-c)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  101 |                 arr_out.at(offset_out) = static_cast<out_type>(*ptr_in);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  102 |                 // recursion here
      |                 ~~~~~~~~~~~~~~~~~
  103 |                 copy_idx(sidx, dim - 1);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~
  104 |             }
      |             ~       
  105 |         };
      |         ~           
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp:75:20: error: ‘modmesh::python::TypeBroadcastImpl<T, D>::broadcast<bool, bool>::<lambda(modmesh::python::TypeBroadcastImpl<bool, bool>::shape_type, int)>’ declared with greater visibility than the type of its field ‘modmesh::python::TypeBroadcastImpl<T, D>::broadcast<bool, bool>::<lambda(modmesh::python::TypeBroadcastImpl<bool, bool>::shape_type, int)>::<arr_new capture>’ [-Werror=attributes]
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp: In instantiation of ‘static void modmesh::python::TypeBroadcastImpl<T, D>::broadcast(modmesh::SimpleArray<U>&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool; D = signed char]’:
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp:162:52:   required from ‘static void modmesh::python::TypeBroadcast<T>::broadcast(modmesh::SimpleArray<U>&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:329:36:   required from ‘static void modmesh::python::WrapSimpleArray<T>::broadcast_array_using_slice(modmesh::python::WrapSimpleArray<T>::wrapped_type&, const std::vector<modmesh::small_vector<int> >&, const pybind11::array&) [with T = bool; modmesh::python::WrapSimpleArray<T>::wrapped_type = modmesh::SimpleArray<bool>]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:187:44:   required from ‘static void modmesh::python::WrapSimpleArray<T>::setitem_parser(modmesh::python::WrapSimpleArray<T>::wrapped_type&, const pybind11::args&) [with T = bool; modmesh::python::WrapSimpleArray<T>::wrapped_type = modmesh::SimpleArray<bool>]’
/home/mujin/modmesh/cpp/modmesh/python/wrapper/modmesh/wrap_SimpleArray.cpp:143:33:   required from ‘modmesh::python::WrapSimpleArray<T>::WrapSimpleArray(pybind11::module&, const char*, const char*) [with T = bool; pybind11::module = pybind11::module_]’
/home/mujin/modmesh/cpp/modmesh/python/common.hpp:266:29:   required from ‘static modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedBase>::wrapper_type& modmesh::python::WrapBase<Wrapper, Wrapped, Holder, WrappedB [...]

2022-10-03 11:20 UTC, yungyuc commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
It has something to do with https://gcc.gnu.org/wiki/Visibility .  And I wonder why don't you use `auto` for holding the lambda?  It does not seem that you are using the lambda outside the static member function function, and a `std::function` seems to be an overkill.

2022-10-03 11:36 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
I didn't use `auto` here because I had a deduction error. I don't know if it is able to address, so I just changed to use `std::function`

If I write as 
```
            auto copy_idx = [&](shape_type sidx, int dim) -> void
            {
            // ....
```

```
 error: use of ‘copy_idx’ before deduction of ‘auto’
 ```

2022-10-03 11:45 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
umm.. Related reading
[I thinks it's because I use it in recursive way, so the program cannot deduct it](https://stackoverflow.com/questions/2067988/recursive-lambda-functions-in-c11)

2022-10-03 11:48 UTC, yungyuc commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
Then why don't you make it a static member function or a standalone helper class template?

2022-10-03 11:57 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
> Then why don't you make it a static member function or a standalone helper class template?
sorry :(, I don't get it, could you explain what is the idea?

2022-10-03 11:58 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
do you mean making `copy_idx` a standalone class? Is it too complicated and unclear for the code?

2022-10-03 12:13 UTC, yungyuc commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +        std::function<void(shape_type, int)> copy_idx;
Yes.  A static member function, free function, or a helper class are worth a try.  I can only tell the complexity after seeing the code.

2022-10-04 13:23 UTC, tigercosmos commented
@yungyuc  please take a look, also the failed CI is not my problem I thought.

2022-10-04 14:01 UTC, yungyuc requested changes

2022-10-04 14:01 UTC, yungyuc commented on cpp/modmesh/buffer/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/TypeBroadcast.cpp
I only see `TypeBroadcast.hpp`, but it is not in this directory.  Where is `TypeBroadcast.hpp`?

2022-10-04 14:01 UTC, yungyuc commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +template <typename T /* original type */, typename D /* for destination type */>
I feel we have a better way to implement this using helper code in pybind11, but it's a good step forward to move the code to a distinct file!

2022-10-04 14:37 UTC, yungyuc commented
> @yungyuc please take a look, also the failed CI is not my problem I thought.

It's not from your change, but upgrade of clang-tidy to v15 on the gha hosted runner.  I will fix it using #126 .  Can you rebase to master once that PR is merged?

2022-10-05 08:39 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +template <typename T /* original type */, typename D /* for destination type */>
could you provide some examples about "helper code in pybind11"?

2022-10-05 08:41 UTC, tigercosmos commented
> It's not from your change, but upgrade of clang-tidy to v15 on the gha hosted runner. I will fix it using https://github.com/solvcon/modmesh/pull/126 . Can you rebase to master once that PR is merged?

I just pull the master, please squash the PR when you merge it.

2022-10-05 08:42 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +template <typename T /* original type */, typename D /* for destination type */>
> it's a good step forward to move the code to a distinct file!

ya, now the wrapper looks more clear. :)

2022-10-05 09:15 UTC, yungyuc requested changes
Please rebase.  If you want to squash you can do it as you rebase.

2022-10-05 10:30 UTC, tigercosmos commented
I've rebased it.

2022-10-05 10:31 UTC, tigercosmos commented on cpp/modmesh/python/wrapper/modmesh/TypeBroadcast.hpp
> +template <typename T /* original type */, typename D /* for destination type */>
@yungyuc Could you answer the question above, I am curious about it. thanks!

2022-10-05 10:48 UTC, yungyuc requested changes

2022-10-05 10:48 UTC, yungyuc commented on cpp/modmesh/python/wrapper/modmesh/CMakeLists.txt
> +    ${CMAKE_CURRENT_SOURCE_DIR}/TypeBroadcast.hpp
This is a header, not source.  Please fix.

2022-10-05 23:21 UTC, merged

2022-10-05 23:21 UTC, yungyuc commented
LGTM.  Thanks.