Add app: cavity flow(draft)
solvcon/solvcon pull request #200
Opened 2023-03-25 10:06 UTC by EN-Chou

This PR includes two apps: `cavity2d_noQt` and `cavity2d`. Both apps share the same code, but differ in their pipeline and status monitoring. `cavity2d_noQt` does not include Qt code in the pipeline, while `cavity2d` does. Additionally, `cavity2d_noQt` can be monitored through printed information in the terminal, while in `cavity2d`, status information is only visible in Modmesh Viewer when the app is halted with `<ctrl> + C` in the terminal.

2023-03-26 02:17 UTC, yungyuc requested changes
Please see the comments in line for improvement.

2023-03-26 02:17 UTC, yungyuc commented on Makefile
> +CMAKE_PREFIX_PATH ?=/usr/local/Qt-6.3.1/
Please do not hard-code `CMAKE_PREFIX_PATH`.

2023-03-26 02:17 UTC, yungyuc commented on cpp/modmesh/view/RManager.cpp
> +        this->addApplication(QString("cavity2d_noQt"));
`cavity2d` and `cavity2d_noQt` look similar and should be merged into one module/app.

2023-03-26 02:17 UTC, yungyuc commented on modmesh/app/cavity2d.py
> +# flake8: noqa
Do not turn off flake8 unconditionally.

2023-03-26 08:28 UTC, EN-Chou commented
[x] edit CMAKE_PREFIX_PATH
[ ] merge `cavity2d_noQt` and `cavity2d`
[ ] revise the use of flake8

2023-03-29 05:35 UTC, yungyuc requested changes
I suggest to squash the multitude of the commits of this PR.

2023-03-29 05:35 UTC, yungyuc commented on modmesh/app/cavity2d.py
> +N = 81
Please avoid using so many global variables.  Instead, create a class to hold all the values and pass it to the functions or classes that need them.

2023-03-29 05:35 UTC, yungyuc commented on modmesh/app/cavity2d.py
> +x_b = [0, 0.0625, 0.0703, 0.0781, 0.0938, 0.1563, 0.2266, 0.2344, 0.5000, 0.8047, 0.8594, 0.9063, 0.9453, 0.9531, 0.9609, 0.9688, 1.0]  # noqa: E501
You should not use lines that are too long.  Please shorten and remove skipping E501.

2023-03-29 06:25 UTC, EN-Chou commented
@yungyuc thanks for your feedback. The revision checklist will include:
- [ ] Shorten lines and remove skipping E501.
- [ ] Create a class to hold all the values and pass it to the functions or classes.
- [ ] Squash commits in this PR.

2023-04-04 14:32 UTC, yungyuc commented
Next time you update the PR please copy the tasks to the PR description body.  Github shows the number of tasks done and remaining.  It will be easier to track the progress.

2023-04-27 07:06 UTC, yungyuc commented
@EN-Chou could you please comment at the code to summarize what you updated?  It has been a while.  Your summary helps a lot for review.

2023-04-27 07:37 UTC, EN-Chou commented
> @EN-Chou could you please comment at the code to summarize what you updated? It has been a while. Your summary helps a lot to the review.

I apologize for not mentioning earlier that the current status of the project is not yet ready for review. Last week, I made a mistake when using rebase and ended up force pushing, which caused some problems. However, these issues were resolved during the meetup yesterday. There are still a few remaining mistakes that need to be addressed, and I will provide a summary of these shortly.

2023-04-27 13:31 UTC, yungyuc commented
I see.  It would help the community know the nature of the updates are not for review by making an explicit comment saying that.  Marking a PR work in progress does not stop people from seeing the updates, and we cannot tell whether or not the updater wants it to be reviewed or not.  Explicit is better than implicit.

2024-04-20 14:38 UTC, tigercosmos commented
@EN-Chou do you want to continue the PR?

2024-04-23 12:24 UTC, yungyuc commented
@EN-Chou if you don't respond by the end of this week, I will close this PR.

2024-04-30 11:24 UTC, closed without merging