add createSimpleArray to wrap WrapSimpleArray
solvcon/solvcon pull request #237
Opened 2023-10-06 04:24 UTC by terrychan999

This is a more detailed version of my example: https://github.com/solvcon/modmesh/issues/27#issuecomment-1732625041
Which can handle (numpy array) or (shape, type) or (shape, value, type) now.

2023-10-06 13:47 UTC, yungyuc requested changes
Thanks, @terrychan999 .  The PR is a good start for us to discuss what we really want.  Please take a look at the inline comments.

And I'd like this work to be compatible to https://data-apis.org/array-api/latest/ (additional read: https://labs.quansight.org/blog/scipy-array-api).

2023-10-06 13:47 UTC, yungyuc commented on cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
> +    if (kwargs.contains("type"))
Numpy uses `dtype` instead of `type`.  We should be consistent to numpy.

2023-10-06 13:47 UTC, yungyuc commented on cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp
> +    mod.def("SimpleArray", &createSimpleArray);
This is not a class (type), but a helper function using the class naming convention.  The returned type depends on the input argument, e.g.,

```python
type(SimpleArray((2, 3), dtype='int32'))) != type(SimpleArray((2, 3), dtype='float32')))
```

But we want the are the same type.  Thus, in the pybind11 wrapper, there should be a Python type created as a facade.

2023-10-20 16:32 UTC, terrychan999 commented
To expose single type to Python, I'm planning to introduce a base class, `SimpleArrayBase` for `WrapSimpleArray<T>`, inspired by tigercosmos's example https://github.com/solvcon/modmesh/issues/27#issuecomment-1203078356.

2023-10-21 05:35 UTC, yungyuc commented
> To expose single type to Python, I'm planning to introduce a base class, `SimpleArrayBase` for `WrapSimpleArray<T>`, inspired by tigercosmos's example [#27 (comment)](https://github.com/solvcon/modmesh/issues/27#issuecomment-1203078356).

It's worth trying.  When do you think it may be ready for review?

2023-10-21 05:58 UTC, terrychan999 commented
I think I need one week to work on it.
That is on 10/29 to be ready for review.

2024-03-23 16:16 UTC, tigercosmos commented
@yungyuc  let's close this PR since we have `SimpleArrayPlex` now.

2024-03-24 02:36 UTC, yungyuc commented
Sounds good, @tigercosmos .  Any comments, @terrychan999 ?

2024-04-06 03:51 UTC, yungyuc commented
@terrychan999 any comments?

2024-04-08 12:55 UTC, terrychan999 commented
> @yungyuc let's close this PR since we have `SimpleArrayPlex` now.
> Sounds good, @tigercosmos . Any comments, @terrychan999 ?

Certainly, @yungyuc and @tigercosmos. I'm grateful for the guidance!

2024-04-09 12:18 UTC, closed without merging

2024-04-09 12:18 UTC, yungyuc commented
Thanks, @tigercosmos @terrychan999