Feature/parameter
solvcon/solvcon pull request #246
Opened 2023-10-21 05:53 UTC by buganini

Requirement:pip3 install QPUIQ==0.3

2023-10-21 07:50 UTC, yungyuc requested changes
Thanks, @buganini .  Some items to change:

- [ ] Use C++ singleton for globals
- [ ] Use dynamic hierarchical toggles
- [ ] CI needs to be clean

Discussions:

Is it possible to have a simple unit test?

2023-10-21 07:50 UTC, yungyuc commented on cpp/modmesh/view/RParameter.cpp
> +static int int64V = 5566;
I think the global static data should be managed by a singleton.  The singleton will make it possible for testing in Python (pytest).

2023-10-21 07:50 UTC, yungyuc commented on cpp/modmesh/view/RParameter.cpp
> +void addParam(const char *key, T *ptr) {
Would it be possible to store the parameter information in the hierarchical dynamic toggle: https://github.com/solvcon/modmesh/blob/1bd05322720e3ce4064c7c36acccd44081c68bf1/tests/test_toggle.py#L280 ?

More information about modmesh toggles: https://github.com/solvcon/modmesh/blob/1bd05322720e3ce4064c7c36acccd44081c68bf1/cpp/modmesh/toggle/toggle.hpp#L220

2023-10-21 07:58 UTC, buganini commented
![image](https://github.com/solvcon/modmesh/assets/72935/d5fe2cb4-61f3-45de-884a-1c42cce22048)

2023-10-21 07:59 UTC, yungyuc requested changes
- [ ] Please add copyright notice to Python files under the `modmesh` package

2023-10-21 07:59 UTC, yungyuc commented on modmesh/params.py
> +from PUI.PySide6 import *
Please add license text.

2023-10-22 08:43 UTC, buganini commented
flake8 issue is fixed

2023-10-25 00:59 UTC, merged

2023-10-25 01:15 UTC, yungyuc commented
I merged the code so that we can move on.  A follow up ticket #247 is filed.