Add new menu to draw a mesh
solvcon/solvcon pull request #282
Opened 2024-03-04 02:49 UTC by YenPeiChen07

This PR is related with #276

There are 3 changes: 
1. created a new menu called `Mesh` to  collect the mesh example. Currently, it only has one item `load_mh_3dmix`. 
2. enlarge sub-window size to make it view easier.
3. change the camera position to have a good view initially.
 
When selecting the menu item, the mesh will be drawn in a sub-window in the viewer.

- Select `load_mh_3dmix` then draw the mesh in sub-window. 
<img width="1510" alt="Screenshot 2024-03-04 at 9 21 16 AM" src="https://github.com/solvcon/modmesh/assets/55582907/f84c4c89-3632-41e8-ae64-aabb1e995e1f">

- Load the mesh again. Manually adjust right sub-window size to check out the result.
<img width="1510" alt="Screenshot 2024-03-04 at 9 21 43 AM" src="https://github.com/solvcon/modmesh/assets/55582907/96e13b1d-349c-400c-a7bc-b84b187c9e9a">

2024-03-04 14:22 UTC, yungyuc requested changes
Please make some changes:
- [x] Move the "Mesh" menu to be right after "File".
- [x] Avoid changing the initial camera direction globally.
- [x] If `help_3dmix` is not required, remove it.
- [ ] Please make sure all CI tasks are good before requesting next review (Python linter fails: https://github.com/solvcon/modmesh/actions/runs/8135138740/job/22239175666?pr=282#step:11:32)

You can use your fork to run the CI by turning it on in the setting:

<img width="1143" alt="image" src="https://github.com/solvcon/modmesh/assets/399122/0bab800a-5567-4124-a0e0-0a51e73f5d19">

2024-03-04 14:22 UTC, yungyuc commented on cpp/modmesh/view/R3DWidget.cpp
> +    camera->setPosition(QVector3D(1.0f, 2.0f, 8.0f));
This changes the initial camera direction for all apps.  Don't do this global change at this point.  Please revert this or make it configurable from Python and set it from the new menu item.

2024-03-04 14:22 UTC, yungyuc commented on cpp/modmesh/view/RManager.cpp
> +        subwin->resize(400, 300);
This makes sense.

2024-03-04 14:22 UTC, yungyuc commented on modmesh/app/mh_3dmix.py
> +Show sample mesh
Please add more description in the module docstring.

2024-03-04 14:22 UTC, yungyuc commented on modmesh/app/mh_3dmix.py
> +def help_3dmix(set_command=False):
This function is not called.  Are you sure it's needed?

2024-03-08 05:57 UTC, YenPeiChen07 commented
@yungyuc, I have updated the code for the requested changes. 

Currently, "Mesh" menu is right after "File" and revert the camera position to original one. Additionally, the console will display the number of edges of the mesh when drawing the mesh.

<img width="1512" alt="Screenshot 2024-03-08 at 1 49 46 PM" src="https://github.com/solvcon/modmesh/assets/55582907/bd5fd0ec-93fa-40d2-a3ad-234b4c640bb9">

2024-03-09 02:06 UTC, yungyuc approved these changes
LGTM

2024-03-09 02:06 UTC, merged