temporarily disable testhelper
solvcon/solvcon pull request #288
Opened 2024-03-10 09:14 UTC by tigercosmos

a quick workaround for #287.

2024-03-10 09:20 UTC, tigercosmos commented
@yungyuc please have a look.

2024-03-10 09:25 UTC, tigercosmos commented
Github macos-13 CI starts to fail because of brew install, but macos-14 already proves the correctness.

2024-03-10 23:57 UTC, yungyuc requested changes
- [ ] Use skip/expect

2024-03-10 23:57 UTC, yungyuc commented on tests/test_buffer.py
> +        return
Please use a proper skip/expect (see https://docs.python.org/3/library/unittest.html#skipping-tests-and-expected-failures) instead an arbitrary return.

2024-03-10 23:58 UTC, yungyuc commented
> Github macos-13 CI starts to fail because of brew install, but macos-14 already proves the correctness.

macos 13 failures are annoying.  Please file an issue and try to resolve it soon too.

2024-03-11 00:25 UTC, tigercosmos commented
@yungyuc already used `skip()` for the test, also filed an issue about macos-13.

2024-03-11 11:47 UTC, yungyuc approved these changes
LGTM

2024-03-11 11:48 UTC, merged