refactor RadixTree
solvcon/solvcon pull request #298
Opened 2024-03-22 07:27 UTC by tigercosmos

The `TimedEntry` struct located in `RadixTree.hpp` is intended for testing purposes. Let's relocate the struct to the test file.

2024-03-22 07:27 UTC, tigercosmos commented
cc @q40603  @yungyuc

2024-03-22 07:37 UTC, yungyuc requested changes
- [ ] Rename the class for the test code to be like test code.

2024-03-22 07:37 UTC, yungyuc commented on gtests/test_nopython_radixtree.cpp
> +class TimedEntry
Moving the test code here makes sense to me.  What do you think, @q40603 ?

We have another `TimedEntry` at https://github.com/solvcon/modmesh/blob/d6ed9ac95f449ff77eb6e4d379c83d25f60eac23/cpp/modmesh/toggle/profile.hpp#L102 

For the test code here, what about renaming it to be different from `modmesh::TimedEntry` there?

2024-03-22 07:56 UTC, tigercosmos commented on gtests/test_nopython_radixtree.cpp
> +class TimedEntry
renamed.

2024-03-22 08:22 UTC, yungyuc approved these changes
LGTM.  Wait for @q40603 comments

2024-03-27 12:50 UTC, q40603 commented
@tigercosmos 
Sorry for the late response.
Separating the TimedEntry class from Radix Tree is more elegant, and it also makes more sense as Radixtree should accept other objects as well.

2024-03-28 11:44 UTC, merged

2024-03-28 11:44 UTC, yungyuc commented
Great!  Thank you @tigercosmos and @q40603