Adjust the boundary plotting
solvcon/solvcon pull request #338
Opened 2024-06-01 07:30 UTC by Gene0315

Following the issue https://github.com/solvcon/modmesh/discussions/335
The PR sets the value at boundary point equal to the inside one.

Features: The plotting looks more reasonable than the original one.
Strength: The adjustment is simple and makes the result look nicer.
Weakness: This way is too artificial and simplified and lack of physical basis. The result shows that there is still something wrong on the boundary, especially the left boundary.

<img width="736" alt="截圖 2024-06-01 下午2 42 33" src="https://github.com/solvcon/modmesh/assets/165459695/ce79e197-1478-4764-9944-39907e197b2f">

2024-06-01 07:50 UTC, yungyuc requested changes
Thanks, @Gene0315 .  This is a good starting point.  I agree this is a very each patch but it may be too easy to be useful.  The modification changes the outside points in a purely artificial way and one cannot predict the approach based on the understandings of the CESE method nor the boundary-condition treatment.  It makes it hard to maintain (understand).

This modification changes the solution array instead of changing the way we plot the array.  A more reasonable way is to just change the plotting code.

There may be follow-up work for enhancing the solution array size once the plotting is made more beautiful.

2024-06-01 07:51 UTC, yungyuc commented
@j8xixo12 comments?

2024-06-01 08:13 UTC, j8xixo12 commented
> @j8xixo12 comments?

I agree with @yungyuc viewpoint, we should modify the plotting code not the solution data, because modifying solution data may effect the computation result, but plotting code not.
I think we can work together to enhance the plotting code !

2024-06-01 08:58 UTC, Gene0315 commented
> > @j8xixo12 comments?
> 
> I agree with @yungyuc viewpoint, we should modify the plotting code not the solution data, because modifying solution data may effect the computation result, but plotting code not. I think we can work together to enhance the plotting code !

Ok, I know what I did improperly. I will try to revise the code in plotting section without changing the solution data.
The first thing I plan to do is to remove the boundary point on the figure.

2024-06-02 12:41 UTC, yungyuc commented
That sounds like a good next step, @Gene0315 .  When do you plan to be ready for the next review?

When you are ready, please annotate the important lines like what was done in https://github.com/solvcon/modmesh/pull/337#discussion_r1622530961 and other PRs.  And also leave a global comment explicitly saying that you are ready for the next review.  If anything is not clear to you, go to the discord channel to ask for help.

2024-06-04 16:13 UTC, Gene0315 commented
@yungyuc
I think I can finish it this Friday or Saturday.

2024-08-25 08:24 UTC, yungyuc commented
> @yungyuc I think I can finish it this Friday or Saturday.

@Gene0315 We forgot to track this.  Any update?

2026-02-07 06:20 UTC, closed without merging