Add Reset within View menu
solvcon/solvcon pull request #375
Opened 2024-06-23 08:00 UTC by YenPeiChen07

Hi @yungyuc and @tychuang1211,

This PR is related to camera improvement in #70. 

I added a Reset menu item under View menu. When clicking it (or pressing `esc` key), objects in all subwindows will be reset to initial state. 

Here are some demo images:

<img width="1510" alt="Screenshot 2024-06-23 at 3 44 22 PM" src="https://github.com/solvcon/modmesh/assets/55582907/37bf1619-0a47-481d-a3ca-484bccc99cae">

The initial mesh object:
<img width="1512" alt="Screenshot 2024-06-23 at 3 16 34 PM" src="https://github.com/solvcon/modmesh/assets/55582907/d3026041-5f2c-48bd-ab88-dea182a70ecb">

Reset to initial state:
<img width="1512" alt="Screenshot 2024-06-23 at 3 16 56 PM" src="https://github.com/solvcon/modmesh/assets/55582907/c91ed05b-00bf-487d-80f8-b8f915be5dac">

2024-06-23 08:04 UTC, yungyuc requested changes
This looks good.  Could you please provide a Python wrapper to the reset function?  The Python wrapper should also take an optional argument for the value that the camera is reset to.

And don't forget to run linter before pushing.

2024-06-23 13:14 UTC, yungyuc commented
@j8xixo12 Could you please also help take a look?

2024-06-23 14:24 UTC, YenPeiChen07 commented
> This looks good. Could you please provide a Python wrapper to the reset function? The Python wrapper should also take an optional argument for the value that the camera is reset to.
> 
> And don't forget to run linter before pushing.

Ok, I would take a look how to implement a Python wrapper to the reset function.

2024-06-23 14:35 UTC, j8xixo12 commented on cpp/modmesh/view/R3DWidget.cpp
> +    camera->setPosition(QVector3D(0.0f, 0.0f, 10.0f));
Is possible to determine the z-axis position of the camera based on the size of the displayed object ?
If the object is too large, the camera might too close then the entire object will not be fitted in the screen.

2024-06-24 01:30 UTC, yungyuc commented
> Ok, I would take a look how to implement a Python wrapper to the reset function.

Thanks, @YenPeiChen07 .  Let's sync up again later this week.

2024-06-26 09:08 UTC, YenPeiChen07 commented on cpp/modmesh/view/R3DWidget.cpp
> +    camera->setPosition(QVector3D(0.0f, 0.0f, 10.0f));
Thanks for feedback. I will research it further.

2024-06-26 09:20 UTC, YenPeiChen07 commented
@yungyuc, 

I added a python wrapper to the reset function in `wrap_view.cpp`. 

By default, the camera is reset to (0.0, 0.0, 10.0) when calling `.resetCamera()`. User can pass a coordinate value they want by calling `.resetCamera(positionX, positionY, positionZ)` in python console.

2024-06-26 13:04 UTC, yungyuc approved these changes
LGTM.  This is a simple addition.  Let's add more enhancements with or on top of it.

2024-06-26 13:04 UTC, yungyuc commented on cpp/modmesh/view/R3DWidget.hpp
> +                     float positionX = 0.0f,
I am not sure using default parameters here is good for maintenance.  If no one objects, we can leave it here and observe.  (My hunch feeling is that it's gonna bite us soon.  We'll see.)

2024-06-26 13:04 UTC, merged