Add vim modeline.
solvcon/solvcon pull request #420
Opened 2024-08-28 12:10 UTC by dragonwu0919

I add vim modeline 

https://github.com/solvcon/modmesh/blob/3211479bce05b31a7a483085df6eb7f5a4fa7c94/cpp/modmesh/buffer/SimpleArray.cpp#L519

2024-08-28 12:17 UTC, dragonwu0919 commented
By the way, I have found many modeline written in different form. Should these modeline be re-written?

for example, instead of `// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:`, some the other forms could be:

https://github.com/solvcon/modmesh/blob/3211479bce05b31a7a483085df6eb7f5a4fa7c94/cpp/modmesh/buffer/BufferExpander.hpp#L143

https://github.com/solvcon/modmesh/blob/3211479bce05b31a7a483085df6eb7f5a4fa7c94/cpp/modmesh/buffer/pymod/buffer_pymod.cpp#L64

2024-08-28 12:32 UTC, tigercosmos commented
I think we can use the longest version as it includes all other versions' settings. 🤔

2024-08-28 13:11 UTC, dragonwu0919 commented
@yungyuc I have added one vim modeline. Please help me review it. Thank.

2024-08-28 15:39 UTC, ThreeMonth03 commented
In [modmesh/gtests/](https://github.com/solvcon/modmesh/tree/master/gtests), it seems that the vim modeline should be added in some of the files. @dragonwu0919, could you please check more files and add the missing vim modelines? Thank you.

2024-08-29 02:03 UTC, yungyuc commented
> In [modmesh/gtests/](https://github.com/solvcon/modmesh/tree/master/gtests), it seems that the vim modeline should be added in some of the files. @dragonwu0919, could you please check more files and add more missing vim modelines? Thank you.

I concur.  @dragonwu0919 it will help you get familiar with the code base by scanning through all files for a specific style conformity/violation.  Why don't you compile a list of all files that need to fix for the modeline?

2024-08-29 07:38 UTC, dragonwu0919 commented
@ThreeMonth03 Sure, I can help add the missing vim modeline back.

@yungyuc Thank you for the review and the suggestion. I will try to compile them when finding the fixing modelines.

2024-08-29 08:10 UTC, ThreeMonth03 commented
> @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> 
> @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.

It looks like you've successfully rebased and squashed the commits. @dragonwu0919, could you please remove the "Add Vim modelines 2" commit? Thank you.

2024-08-29 08:30 UTC, dragonwu0919 commented
> > @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> > @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.
> 
> It looks like you've successfully rebased and squashed the commits. @dragonwu0919, could you please remove the "Add Vim modelines 2" commit because it is meaningless? Thank you.

@ThreeMonth03 Sorry for asking a basic question, but may i ask how to remove that commit? My powershell says that the commit "Add Vim modeline 2" has been deleted in my local repo.
```
PS C:\SciWork\modmesh> git log --oneline
cbfa15a (HEAD -> CodeStyle) Add vim modeline.
f7195c7 (origin/master, origin/HEAD, master) Merge pull request #418 from Tucchhaa/expose_camera_api_python
42161b5 apply review 2
``

2024-08-29 08:35 UTC, ThreeMonth03 commented
> > > @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> > > @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.
> > 
> > 
> > It looks like you've successfully rebased and squashed the commits. @dragonwu0919, could you please remove the "Add Vim modelines 2" commit because it is meaningless? Thank you.
> 
> @ThreeMonth03 Sorry for asking a basic question, but may i ask how to remove that commit? My powershell says that the commit "Add Vim modeline 2" has been deleted in my local repo.
> 
> ```
> PS C:\SciWork\modmesh> git log --oneline
> cbfa15a (HEAD -> CodeStyle) Add vim modeline.
> f7195c7 (origin/master, origin/HEAD, master) Merge pull request #418 from Tucchhaa/expose_camera_api_python
> 42161b5 apply review 2
> ``
> ```

Sorry for my unclear explanation. I think you should rebase and reword the commit `cbfa15a`, and you could refer the note to do it.

2024-08-29 08:47 UTC, ThreeMonth03 commented
> > > @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> > > @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.
> > 
> > 
> > It looks like you've successfully rebased and squashed the commits. @dragonwu0919, could you please remove the "Add Vim modelines 2" commit because it is meaningless? Thank you.
> 
> @ThreeMonth03 Sorry for asking a basic question, but may i ask how to remove that commit? My log shows that the commit "Add Vim modeline 2" has been deleted in my local repo.
> 
> ```
> PS C:\SciWork\modmesh> git log --oneline
> cbfa15a (HEAD -> CodeStyle) Add vim modeline.
> f7195c7 (origin/master, origin/HEAD, master) Merge pull request #418 from Tucchhaa/expose_camera_api_python
> 42161b5 apply review 2
> ```

BTW, if you enter `git log` in your terminal, you should see that the second line of the commit `cbfa15a` is `Add Vim modeline 2`, and you could reword the commit `cbfa15a` and remove this line in the commit message.

2024-08-29 08:59 UTC, ThreeMonth03 commented
Thanks, @dragonwu0919, the commit message is satisfying.

2024-08-29 08:59 UTC, dragonwu0919 commented
> > > > @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> > > > @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.
> > > 
> > > 
> > > It looks like you've successfully rebased and squashed the commits. @dragonwu0919, could you please remove the "Add Vim modelines 2" commit because it is meaningless? Thank you.
> > 
> > 
> > @ThreeMonth03 Sorry for asking a basic question, but may i ask how to remove that commit? My log shows that the commit "Add Vim modeline 2" has been deleted in my local repo.
> > ```
> > PS C:\SciWork\modmesh> git log --oneline
> > cbfa15a (HEAD -> CodeStyle) Add vim modeline.
> > f7195c7 (origin/master, origin/HEAD, master) Merge pull request #418 from Tucchhaa/expose_camera_api_python
> > 42161b5 apply review 2
> > ```
> 
> BTW, if you enter `git log` in your terminal, you should see that the second line of the commit `cbfa15a` is `Add Vim modeline 2`, and you could reword the commit `cbfa15a` and remove this line in the commit message.

@ThreeMonth03  Thank you for the reminding. I never thought that `--oneline` will function like this. I misunderstand this command to be *squish commit log into one line*, instead of *show only the first line of commit log* .

2024-08-29 09:15 UTC, dragonwu0919 commented
> @ThreeMonth03 Sure, I can help add the missing vim modeline back.
> 
> @yungyuc Thank you for the review and the suggestion. I will try to compile them when fixing modelines.

@yungyuc Sorry for bothering you further. You suggested that I could ***compile*** those files when fixing the modeline problem, but I don't understand what the word ***compile*** means in this context. Should I literally find a compiler to compile the files, or is it just suggesting that I could read the pattern of how the code is written here?

2024-08-30 05:00 UTC, yungyuc commented
> @yungyuc Sorry for bothering you further. You suggested that I could _**compile**_ those files when fixing the modeline problem, but I don't understand what the word _**compile**_ means in this context. Should I literally find a compiler to compile the files, or is it just suggesting that I could read the pattern of how the code is written here?

By "compile a list of all files that need to fix for the modeline", I meant to make a list of all files that need to fix for the modeline.

2024-08-31 06:40 UTC, dragonwu0919 commented
> > @yungyuc Sorry for bothering you further. You suggested that I could _**compile**_ those files when fixing the modeline problem, but I don't understand what the word _**compile**_ means in this context. Should I literally find a compiler to compile the files, or is it just suggesting that I could read the pattern of how the code is written here?
> 
> By "compile a list of all files that need to fix for the modeline", I meant to make a list of all files that need to fix for the modeline.

Understood. I will try my best to do so.

2024-08-31 10:01 UTC, dragonwu0919 commented
@yungyuc The files that have been updated with Vim modelines are listed below. Please review the overall changes. Thank you.

```json
{
    "WithoutModeline":  [
                       ".\\setup.py",
                       ".\\cpp\\modmesh\\buffer\\pymod\\TypeBroadcast.hpp",
                       ".\\cpp\\modmesh\\inout\\pymod\\wrap_Gmsh.cpp",
                       ".\\cpp\\modmesh\\inout\\pymod\\wrap_Plot3d.cpp",
                       ".\\cpp\\modmesh\\onedim\\Euler1DCore.cpp",
                       ".\\cpp\\modmesh\\onedim\\Euler1DCore.hpp",
                       ".\\cpp\\modmesh\\spacetime\\kernel\\BadEuler1DSolver.cpp",
                       ".\\cpp\\modmesh\\spacetime\\kernel\\BadEuler1DSolver.hpp",
                       ".\\cpp\\modmesh\\testhelper\\pymod\\testbuffer_pymod.cpp",
                       ".\\modmesh\\params.py",
                       ".\\modmesh\\app\\euler1d.py",
                       ".\\tests\\test_gmsh.py"
                   ]
}
```

2024-08-31 13:29 UTC, yungyuc requested changes
- [ ] Make sure all line endings uses Unix LF (`\n`).

2024-08-31 13:29 UTC, yungyuc commented on cpp/modmesh/buffer/pymod/TypeBroadcast.hpp
> +\r\n
It seems that you have some lines mixed with [dos/windows CF+LF plain-text line ending](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html).  Please correct them.

You probably did not configure your editor correctly.

2024-08-31 18:20 UTC, ThreeMonth03 reviewed
- [ ] Keep only one newline after the vim modeline.
You may refer [cpp/modmesh/buffer/SimpleArray.cpp](https://github.com/solvcon/modmesh/pull/420/files/33734c6a50b870086706167e41bddc8c9d5c974c#diff-04216ffd67af1f4755bacaae487e30f1bf519d8302cf86fe7864fe08b8182d62) and modify the other files.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/spacetime/kernel/BadEuler1DSolver.hpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
I'm not sure whether there should be a newline between the bracket and the vim modeline. @yungyuc, how do you think?

2024-08-31 18:20 UTC, ThreeMonth03 commented on gtests/test_nopython_callprofiler.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
Missing newline (\n).

2024-08-31 18:20 UTC, ThreeMonth03 commented on modmesh/app/euler1d.py
> +
<img width="553" alt="image" src="https://github.com/user-attachments/assets/8745b29b-669c-4f68-b89e-a666907f5849">

In the editor, it is clear that there are two newlines after the vim modeline, and the github action should fail under this circumstance.
Thus, you may modify this part according to the following rules:
1. There should be only a newline after the vim modeline.
2. The newline should not contain any character, such as the tab `'\t'` and the space ` `.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/buffer/pymod/TypeBroadcast.hpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/inout/pymod/wrap_Gmsh.cpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/inout/pymod/wrap_Plot3d.cpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/onedim/Euler1DCore.cpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/onedim/Euler1DCore.hpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/spacetime/kernel/BadEuler1DSolver.cpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/testhelper/pymod/testbuffer_pymod.cpp
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on gtests/test_nopython_inout.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
missing newline.

2024-08-31 18:20 UTC, ThreeMonth03 commented on gtests/test_nopython_serializable.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
missing newline.

2024-08-31 18:20 UTC, ThreeMonth03 commented on modmesh/params.py
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on setup.py
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on tests/test_gmsh.py
> +
2 newlines.

2024-08-31 18:20 UTC, ThreeMonth03 commented on cpp/modmesh/buffer/SimpleArray.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
There is only one newline after the vim modeline, good job.

2024-09-01 01:20 UTC, yungyuc commented on cpp/modmesh/spacetime/kernel/BadEuler1DSolver.hpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
It is better to leave a blank line between the modeline and the code above it.

2024-09-01 05:49 UTC, dragonwu0919 commented
- [x] Ensured there is only one newline after the modeline.
- [x] Ensured there is a newline between the Vim modeline and the rest of the file content.

Hope it doesn't go wrong this time. @yungyuc, could you please help me review the changes? Thank you!

2024-09-01 06:42 UTC, ThreeMonth03 requested changes
- [ ] Add the missing newline in [gtests/test_nopython_callprofiler.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-f2b5f43898d27aa295793363d34b89b0ef47c3beacb2ed3dd2756797f28f044c), [gtests/test_nopython_inout.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-da7d5e51ea17281d289ead2dc96f790f910914b3492407efc1c3223ba65bf08e) and [gtests/test_nopython_serializable.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-44ff83115bf707eb36686b238dc2a5a150058e3caa924025a68a164819e66163).

@dragonwu0919 I think after the slight modification to the above files, we could merge this pr. Thank's for your contribution.

2024-09-01 06:42 UTC, ThreeMonth03 commented on gtests/test_nopython_callprofiler.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
<img width="460" alt="image" src="https://github.com/user-attachments/assets/2f8e3962-b420-4b3c-bdc1-06813cf5a850">

It seems that you miss to add a newline after the vim modeline.

2024-09-01 06:42 UTC, ThreeMonth03 commented on gtests/test_nopython_inout.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
It seems that you miss to add a newline after the vim modeline.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/af0139c3-d66b-49bd-b29f-b4d52518c739">

2024-09-01 06:42 UTC, ThreeMonth03 commented on gtests/test_nopython_serializable.cpp
> +// vim: set ff=unix fenc=utf8 et sw=4 ts=4 sts=4:
It seems that you miss to add a newline after the vim modeline.

<img width="506" alt="image" src="https://github.com/user-attachments/assets/3c3c6666-a124-4677-b5c5-724c569db83b">

2024-09-01 07:08 UTC, yungyuc commented
> * [ ]  Add the missing newline in [gtests/test_nopython_callprofiler.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-f2b5f43898d27aa295793363d34b89b0ef47c3beacb2ed3dd2756797f28f044c), [gtests/test_nopython_inout.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-da7d5e51ea17281d289ead2dc96f790f910914b3492407efc1c3223ba65bf08e) and [gtests/test_nopython_serializable.cpp](https://github.com/solvcon/modmesh/pull/420/files#diff-44ff83115bf707eb36686b238dc2a5a150058e3caa924025a68a164819e66163).
> 
> @dragonwu0919 I think after the slight modification to the above files, we could merge this pr. Thank's for your contribution.

Agree.

---

It would be nice to have consistent new line after the modeline, but this is indeed very easy to miss when we only review a limited number of source files.

When it is for developing a feature or fixing a bug, the inconsistency at the end of file is fine.  Picking a minor issue like that after a great effort of hacking can be discouraging.

But for a (style) refactoring PR like this, it good to make the style as consistent as possible, because its sole purpose is to make the style perfect.

2024-09-01 08:37 UTC, dragonwu0919 commented
I have completed the modifications for these three files. @yungyuc, @ThreeMonth03, thank you both very much. This experience has really helped me become more familiar with how PRs work.

2024-09-01 08:38 UTC, ThreeMonth03 approved these changes
@dragonwu0919 Thanks for your contribution. Everything looks fine now.

2024-09-01 10:00 UTC, ThreeMonth03 commented
> @dragonwu0919 Thanks for your contribution. Everything looks fine now.

@dragonwu0919 We are sorry to inform you that you haven't pass all of the github workflows, and the detail of the error log could find [here](https://github.com/solvcon/modmesh/actions/runs/10652443284/job/29527238961?pr=420#step:13:31). You must to pass all of the the github action before merging the pr.
![image](https://github.com/user-attachments/assets/30fce559-3372-4525-921a-39929d4608da)

BTW, if you want to run the github action under your repository, you can refer [this article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository), then your repository will run the [github workflows](https://github.com/dragonwu0919/modmesh/action) automatically.

2024-09-01 16:17 UTC, ThreeMonth03 commented
> > @dragonwu0919 Thanks for your contribution. Everything looks fine now.
> 
> @dragonwu0919 We are sorry to inform you that you haven't pass all of the github workflows, and the detail of the error log could find [here](https://github.com/solvcon/modmesh/actions/runs/10652443284/job/29527238961?pr=420#step:13:31). You must to pass all of the the github action before merging the pr. ![image](https://private-user-images.githubusercontent.com/71295942/363481965-30fce559-3372-4525-921a-39929d4608da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMDcyODUsIm5iZiI6MTcyNTIwNjk4NSwicGF0aCI6Ii83MTI5NTk0Mi8zNjM0ODE5NjUtMzBmY2U1NTktMzM3Mi00NTI1LTkyMWEtMzk5MjlkNDYwOGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDE2MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMzI3ZDI1MDFhMTNlMjRiZWU0YzA1YWUxYjc4NWQ3MWNjNTk2YmIyNzAzNDVjNGJiMzE0NTdkNmVkMDQyYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6wEJac6v85YO4z-xgJbgzLNfb-1gQYwV185WlPrJYRQ)
> 
> BTW, if you want to run the github action under your repository, you can refer [this article](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository), then your repository will run the [github workflows](https://github.com/dragonwu0919/modmesh/actions) automatically.

@dragonwu0919, thank you very much. It seems that you correct the errors and pass [the workflows](https://github.com/dragonwu0919/modmesh/actions), and it looks good to me. @yungyuc, you could review this pr when you are available, thank you.

2024-09-02 09:43 UTC, yungyuc approved these changes

2024-09-02 09:43 UTC, merged

2024-09-02 09:43 UTC, yungyuc commented
Thanks, @dragonwu0919 .  Look good to me.  Merging.