ci(viewer): init CI run for viewer binary
solvcon/solvcon pull request #76
Opened 2022-05-23 17:30 UTC by tai271828

Beginning to build the `viewer` binary with Ubuntu Jammy (22.04). The CI job will pass with Ubuntu, and will fail with macos. I leave the fix for macos to anyone with mac. 

Ref issue #75

2022-05-24 12:51 UTC, yungyuc requested changes
Great addition!  Could you fix the failed run and do some minor tweaks?

2022-05-24 12:51 UTC, yungyuc commented on .github/workflows/modmesh_viewer.yml
> +    - name: flake8
We do not need flake8 for this action.

2022-05-24 12:51 UTC, yungyuc commented on .github/workflows/modmesh_viewer.yml
> +          os: [ubuntu-22.04, macos-11]
`macos-11` does not work: https://github.com/tai271828/modmesh/runs/6560081058?check_suite_focus=true#step:7:70 .

2022-05-24 12:51 UTC, yungyuc commented on .github/workflows/modmesh_viewer.yml
> +    - name: dependency (macos)
This is not needed because macos does not build with Qt.

2022-05-24 12:51 UTC, yungyuc commented on .github/workflows/modmesh_viewer.yml
> +    - name: pytest
We do not need pytest.  I think we should make a new unit test runner different from this in the future.

2022-05-24 13:00 UTC, yungyuc commented
@ianlienfa FYI

2022-05-28 10:55 UTC, yungyuc commented on .github/workflows/modmesh_viewer.yml
> +    - name: pytest
I am keeping pytest because this uses a new OS version that is not included in other actions.

2022-05-28 11:11 UTC, yungyuc approved these changes

2022-05-28 11:12 UTC, merged

2022-05-30 15:19 UTC, tai271828 commented
Thanks for the follow-up fixup. I went to a holiday for several days without accessing internet! I hope everyone does not mind the late response.

2022-05-30 23:01 UTC, yungyuc commented
No problem at all.